### ISSUE TITLE
Unable to create UserPoolClientLambda using the cloudformation template

### ISSUE THREAD

**Issue by jkundumanisrinivasan** [aws-samples/amazon-deequ-glue#7]
I tried to deploy the cloudformation stack and got the below error message during the nested stack
amplify-deequconstraints-dev-180625-authdeequconstraints752dc94a-JADASIY5VHWK

Resource handler returned message: "Invalid request provided: The ZipFile attribute is not supported for the runtime 'nodejs14.x'" (RequestToken: 9a87b592-0600-aa62-b3ab-a9b04a857276, HandlerErrorCode: InvalidRequest)

**Comment by jaidisido** [comment]
Thanks for raising, should now be fixed with https://github.com/aws-samples/amazon-deequ-glue/pull/8
